### PR TITLE
Added ability to access the underlying AVCaptureDevice and added isAdjustingX properties.

### PR DESCRIPTION
**Pull request by eyaldar**
Not sure if this is what you meant, but I added access to the capture device and added the "adjustingFocus"/"adjustingExposure"/"adjustingWhiteBalance" properties.

### CODE REVIEW

**Comment by remirobert** [comment]
Thanks for the pull request that's a good contribution. I am looking at it.
Just a question, why put **`** ?

```swift
if let `captureDevice` = captureDevice {
```

**Comment by eyaldar** [comment]
just to avoid the need for another variable name, I'll change it if you prefer a null check and force unwrap.

**Comment by remirobert** [comment]
@eyaldar no no, it's good, I didn't know that. Thanks for the trick. 👍

**Comment by remirobert** [comment]
tested and approved ! 🎉

Thank you @eyaldar for your contribution.

**Pull request merged**
